/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btql;

import btql.categoryman.FrmCategoryManage;
import btql.orderman.FrmOrderManage;
import btql.report.FrmReportTotal;
import btql.userman.FrmUserManage;
import btql.vendorman.FrmVendorManage;
import btql.watchman.FrmWatchManage;

/**
 *
 * @author Computer
 */
public class FrmMain extends javax.swing.JFrame {

    private FrmLogin login;

    /**
     * Creates new form FrmMain
     *
     * @param login
     */
    public FrmMain(FrmLogin login) {
        initComponents();
        this.login = login;

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFunction = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnuBaoCao = new javax.swing.JMenu();
        mnuReportTotal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý cửa hàng đồng hồ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dong-ho-tool-watch-la-gi-co-nhung-loai-nao-.jpg"))); // NOI18N

        mnuFunction.setText("Quản lý");

        jMenuItem1.setText("Quản lý nhân sự");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuFunction.add(jMenuItem1);

        jMenuItem2.setText("Quản lý đồng hồ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuFunction.add(jMenuItem2);

        jMenuItem3.setText("Quản lý nhà sản xuất");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnuFunction.add(jMenuItem3);

        jMenuItem4.setText("Quản lý danh mục");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnuFunction.add(jMenuItem4);

        jMenuItem5.setText("Quản lý hóa đơn");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnuFunction.add(jMenuItem5);

        jMenuBar1.add(mnuFunction);

        mnuBaoCao.setText("Báo cáo");

        mnuReportTotal.setText("Báo cáo doanh thu");
        mnuReportTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportTotalActionPerformed(evt);
            }
        });
        mnuBaoCao.add(mnuReportTotal);

        jMenuBar1.add(mnuBaoCao);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        login.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private btql.userman.FrmUserManage frmUserManage;
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
//        FrmUserManage.load();=
        if (frmUserManage == null) {
            frmUserManage = new FrmUserManage();
        }

        try {
            frmUserManage.load();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private btql.vendorman.FrmVendorManage frmVendorManage;
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if (frmVendorManage == null) {
            frmVendorManage = new FrmVendorManage();
        }

        try {
            frmVendorManage.load();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private btql.categoryman.FrmCategoryManage frmCategoryManage;

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        if (frmCategoryManage == null) {
            frmCategoryManage = new FrmCategoryManage();
        }

        try {
            frmCategoryManage.load();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private btql.watchman.FrmWatchManage frmWatchManage;

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        if (frmWatchManage == null) {
            frmWatchManage = new FrmWatchManage();
        }

        try {
            frmWatchManage.load();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private btql.orderman.FrmOrderManage frmOrderManage;
    
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        if (frmOrderManage == null) {
            frmOrderManage = new FrmOrderManage();
        }
        
        try {
            frmOrderManage.load();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private btql.report.FrmReportTotal frmReportTotal;
    
    private void mnuReportTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportTotalActionPerformed
        // TODO add your handling code here:
        if (frmReportTotal == null) {
            frmReportTotal = new FrmReportTotal();
        }
        
        try {
            frmReportTotal.load();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_mnuReportTotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu mnuBaoCao;
    private javax.swing.JMenu mnuFunction;
    private javax.swing.JMenuItem mnuReportTotal;
    // End of variables declaration//GEN-END:variables
}
