/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btql.watchman;

import btql.watchman.*;
import btql.userman.*;
import btql.*;
import common.DataGridForm;
import daos.CategoryDAO;
import daos.VendorDAO;
import daos.WatchDAO;
import dtos.Category;
import dtos.Vendor;
import dtos.Watch;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Computer
 */
public class DlgUpdate extends javax.swing.JDialog {

    private final ComboBoxModel<Vendor> vendorComboBoxModel;
    private final ComboBoxModel<Category> categoryComboBoxModel;

    /**
     * Creates new form DlgCreate
     */
    public DlgUpdate(DataGridForm parent, boolean modal, int id) throws Exception {
        super(parent, modal);
        
        vendorComboBoxModel = VendorDAO.instance.buildComboBoxModel();
        categoryComboBoxModel = CategoryDAO.instance.buildComboBoxModel();
        
        initComponents();

        setLocationRelativeTo(null);

        setModel(id);
    }

    private Watch defaultModel;

    void setModel(int id) throws Exception {
        Watch watch = WatchDAO.instance.findById(id);
        txtId.setText(Integer.toString(watch.getId()));
        txtTitle.setText(watch.getTitle());
        txtDescription.setText(watch.getDescription());
        spQuantity.setValue(watch.getQuantity());
        spUnitPrice.setValue(watch.getUnitPrice());

        for (int i = 0; i < cbVendor.getModel().getSize(); ++i) {
            if (cbVendor.getModel().getElementAt(i).getId() == watch.getVendorId()) {
                cbVendor.getModel().setSelectedItem(cbVendor.getModel().getElementAt(i));
            }
        }

        for (int i = 0; i < cbCategory.getModel().getSize(); ++i) {
            if (cbCategory.getModel().getElementAt(i).getId() == watch.getCategoryId()) {
                cbCategory.getModel().setSelectedItem(cbCategory.getModel().getElementAt(i));
            }
        }

        defaultModel = watch;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        spQuantity = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spUnitPrice = new javax.swing.JSpinner();
        cbVendor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        cbCategory = new javax.swing.JComboBox<>();
        btnReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cập nhật đồng hồ");

        btnSubmit.setText("Cập nhật");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel2.setText("Mô tả");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        spQuantity.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel3.setText("Số lượng");

        jLabel6.setText("Đơn giá");

        jLabel4.setText("Nhà cung cấp");

        spUnitPrice.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        cbVendor.setModel(vendorComboBoxModel);

        jLabel1.setText("Tên đồng hồ");

        jLabel5.setText("Danh mục");

        cbCategory.setModel(categoryComboBoxModel);

        btnReset.setText("Xóa");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel7.setText("ID");

        txtId.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spUnitPrice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                            .addComponent(spQuantity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbVendor, javax.swing.GroupLayout.Alignment.LEADING, 0, 552, Short.MAX_VALUE)
                            .addComponent(cbCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId))))
                .addGap(59, 104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbVendor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnSubmit))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        try {

            List<String> errors = getFormErrors();
            if (!errors.isEmpty()) {
                JOptionPane.showMessageDialog(this, String.join("\n", errors), "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Watch watch = new Watch();
            watch.setId(defaultModel.getId());
            watch.setTitle(txtTitle.getText());
            watch.setDescription(txtDescription.getText());
            watch.setQuantity((int) spQuantity.getValue());
            watch.setUnitPrice((int) spUnitPrice.getValue());

            watch.setVendorId(((Vendor) cbVendor.getModel().getSelectedItem()).getId());
            watch.setCategoryId(((Category) cbCategory.getModel().getSelectedItem()).getId());
            watch.setUserId(Config.getCurrentUserId());

            WatchDAO.instance.update(watch);
            ((DataGridForm) getOwner()).refresh(true);

            // create
            // update DB
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(DlgCreate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            // TODO add your handling code here:
            setModel(defaultModel.getId());
        } catch (Exception ex) {
            Logger.getLogger(DlgUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private List<String> getFormErrors() throws SQLException {
        List<String> errors = new ArrayList();
        if (txtTitle.getText().equals("")) {
            errors.add("Tiêu đề không được bỏ trống");
        }

        if (cbVendor.getModel().getSelectedItem() == null) {
            errors.add("Nhà cung cấp không được bỏ trống");
        }

        if (cbCategory.getModel().getSelectedItem() == null) {
            errors.add("Danh mục không được bỏ trống");
        }

        return errors;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<Category> cbCategory;
    private javax.swing.JComboBox<Vendor> cbVendor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spQuantity;
    private javax.swing.JSpinner spUnitPrice;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
