/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btql.orderman;

import btql.categoryman.*;
import btql.categoryman.*;
import common.DataGridForm;
import common.DataTable;
import daos.OrderDAO;
import dtos.Order;
import dtos.OrderView;
import dtos.Vendor;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Computer
 */
public class FrmOrderManage extends DataGridForm {

    /**
     * Creates new form FrmOrderManage
     */
    public FrmOrderManage() {
        initComponents();
        setLocationRelativeTo(null);

        txtSearchQuery.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                refresh();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                refresh();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                refresh();
            }
        });

        tblDataGrid.setModel(new DataTable(
                new Object[][]{},
                new String[]{
                    "ID",
                    "Tên khách hàng",
                    "Địa chỉ nhận",
                    "Thời gian",
                    "Nhân viên tạo",
                    "Tổng tiền"
                }
        ));

        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tblDataGrid.getColumnModel().getColumn(5).setCellRenderer(rightRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataGrid = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        btnCreate = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnView = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        txtSearchQuery = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý đơn hàng");

        tblDataGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "Username", "Owner"
            }
        ));
        tblDataGrid.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDataGrid.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tblDataGridCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblDataGrid);

        jToolBar2.setRollover(true);

        btnCreate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(0, 102, 0));
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-add-link-50.png"))); // NOI18N
        btnCreate.setText("Thêm mới");
        btnCreate.setFocusable(false);
        btnCreate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCreate.setPreferredSize(new java.awt.Dimension(100, 100));
        btnCreate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        jToolBar2.add(btnCreate);
        jToolBar2.add(jSeparator2);

        btnView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(0, 102, 0));
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-pencil-50 (2).png"))); // NOI18N
        btnView.setText("Xem");
        btnView.setFocusable(false);
        btnView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnView.setPreferredSize(new java.awt.Dimension(100, 100));
        btnView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jToolBar2.add(btnView);
        jToolBar2.add(jSeparator3);

        txtSearchQuery.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtSearchQueryCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jLabel1.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        new DlgCreate(this, true).setVisible(true);

    }//GEN-LAST:event_btnCreateActionPerformed

    int getCurrentSelected() {
        // row selected
        int selectId = tblDataGrid.getSelectedRow();
        if (selectId == -1) {
            return -1;
        }

        int id = Integer.valueOf(tblDataGrid.getModel().getValueAt(selectId, 0).toString());

        return id;
    }

    private void tblDataGridCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblDataGridCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataGridCaretPositionChanged

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selected = getCurrentSelected();
        if (selected == -1) {
            return;
        }

        try {
            new DlgView(this, true, selected).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FrmOrderManage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtSearchQueryCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtSearchQueryCaretPositionChanged

    }//GEN-LAST:event_txtSearchQueryCaretPositionChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOrderManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOrderManage().setVisible(true);
            }
        });
    }

    public void load() throws Exception {
        refresh();
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTable tblDataGrid;
    private javax.swing.JTextField txtSearchQuery;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh(boolean reset) {
        try {
            List<OrderView> items = OrderDAO.instance.findAll(txtSearchQuery.getText());

            DefaultTableModel model = (DefaultTableModel) tblDataGrid.getModel();
            model.setRowCount(0);

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            for (OrderView n : items) {
                Object dataRow[] = new Object[6];
                dataRow[0] = n.getId();
                dataRow[1] = n.getCustomerName();
                dataRow[2] = n.getCustomerAddress();
                dataRow[3] = sdf.format(n.getCreatedAt());
                dataRow[4] = n.getUsername();
                dataRow[5] = Integer.toString(n.getTotal()) + " VND";
                model.addRow(dataRow);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DlgCreate.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
